[workspace]
resolver = "3"
members = [
    "germterm",
    "examples/hello-world",
    "examples/standard-blending",
    "examples/octad-merging",
    "examples/octad-particles",
    "examples/twoxel-tester",
    "examples/twoxel-snake",
    "examples/particle-benchmark",
]
