[package]
name = "germterm"
description = "A lightweight high-performance terminal graphics framework!"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"

[dependencies]
bitflags = "2.10.0"
crossterm = "0.29.0"
rand = "0.9.2"
